<?php

namespace Database\Seeders\qualification\education\school;

use App\Models\System\Serviceperson\Qualifications\Education\School;
use Illuminate\Database\Seeder;

class PostSecondarySchoolsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $postSecondarySchools = [
            [
                'name' => 'MIC Institute of Technology',
                'slug' => 'MIC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'National Energy Skills Center',
                'slug' => 'NESC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Tobago Hospitality and Tourism Institute',
                'slug' => 'THTI',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'A-Class Draperies & Interiors Limited',
                'slug' => 'A-CLASS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Automation Technology College Limited',
                'slug' => 'ATC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Advanced Solutions Technical Institute Limited',
                'slug' => 'ASTI',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Academy of Tertiary Studies Limited',
                'slug' => 'ATS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Borderless Horizons Medical Associates Hospital Limited',
                'slug' => 'BHMAH',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Business Etiquette & Protocol Specialist Limited',
                'slug' => 'BEPSL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Catholic Religious Education Development Institute Limited',
                'slug' => 'CREDI',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Dawill Law Academy & Consultancy Services Limited',
                'slug' => 'DAWILL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Emergency Training Institute of Trinidad and Tobago Limited',
                'slug' => 'ETITT',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Face and Body Clinic Limited',
                'slug' => 'FABCL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'The International Institute of Cosmetology & Aesthetics Limited',
                'slug' => 'IICA',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Institute of Law and Academic Studies Limited',
                'slug' => 'ILAS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'The Institute of Medical Education Limited',
                'slug' => 'IME',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Institute of Training and Development Limited',
                'slug' => 'INTAD Ltd',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Institute of Tertiary Tutors Limited',
                'slug' => 'ITT',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'K. Beckles and Associates Law Tutors Limited',
                'slug' => 'K Beckles',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Kenson School of Production Technology Limited',
                'slug' => 'KENSON',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Madame Maharaj School of Cosmetology and Hair Designs Limited',
                'slug' => 'MMSCHD',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Omardeen School of Accountancy Limited',
                'slug' => 'OMARDEEN',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Premier Accountancy Specialist School Limited',
                'slug' => 'PASS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Professional Institute of Marketing and Business Studies Limited',
                'slug' => 'PIMBS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'PIXELS Education Limited',
                'slug' => 'PIXELS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Professional School of Accountancy Limited',
                'slug' => 'PSAL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Purchasing Supply and Management Tuition Services Limited',
                'slug' => 'PSMTSL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Students Accountancy Centre Limited',
                'slug' => 'SAC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Sacha Cosmetics Limited',
                'slug' => 'SCL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => ' School of Higher Education Limited',
                'slug' => 'SHEL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'SHEQ Institute Limited',
                'slug' => 'SHEQ',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'School of Refrigeration and Air Conditioning Limited',
                'slug' => 'SORAC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Trinidad Tower Cranes Services Limited',
                'slug' => 'TTCS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Trinidad and Tobago College of Therapeutic Massage Limited',
                'slug' => 'TTCOTMBCL',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Tobago Technical School Limited ',
                'slug' => 'TTS',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
            [
                'name' => 'Trinizuela Technical and Vocational College Limited',
                'slug' => 'TTVC',
                'school_level_id' => 3,
                'school_type_id' => 12,
                'school_district_id' => 9,
                'description' => '',
                'created_at' => now(),
            ],
        ];

        School::insert($postSecondarySchools);
    }
}
