<?php

namespace Database\Seeders\qualification\education\school;

use App\Models\System\Serviceperson\Qualifications\Education\School;
use Illuminate\Database\Seeder;

class SecondarySchoolsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $secondarySchools = [
            [
                'name'=> 'A.S.J.A. Boys\' College, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),

            ],
            [
                'name'=> 'A.S.J.A. Boys\' High School, Charlieville',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'A.S.J.A. Girls\' College, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'A.S.J.A. Girls\' High School, Barrackpore',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'A.S.J.A. Girls\' High School, Charlieville',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'A.S.J.A. Girls\' High School, Tunapuna',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 1,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Abiadama Center for Lifelong Learning',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'AGAPE',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Aranguez Educational Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Aranguez Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Archibald Institute For Girls',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Arima Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Arima Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'BARATARIA INSTITUTE OF SCIENCE',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Barataria Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Barataria Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Barrackpore Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Barrackpore Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bates Memorial High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Belmont Boys\' Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Belmont Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Biche High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bishop Anstey High School, East',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bishop Anstey High School, Port of Spain',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bishop High School, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bishops Centenery College, POS',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Blanchisseuse High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Bon Air High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Brazil High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Carapichaima Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Carapichaima Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Caribbean Union College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Cedros Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Chaguanas Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Chaguanas Prestige Secondary School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Chaguanas Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Class Enterprises, Rio Claro',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Cocorite Learning Centre',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Corinth Teachers Training College 6th Form',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Corpus Christi College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Coryal High school',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Couva Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Couva Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Couva Private Grammar School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Cowen Hamilton Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 3,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Cunupia High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Curepe Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Daniel\'s Educational Institute',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Darul Uloom Boys',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Darul Uloom Girls',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Debe High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'DIEGO MARTIN FINISHING SCHOOL',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Diego Martin Gov\'t Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Diego Martin Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'DOWNER\' S EDUCATIONAL INSTITUTE',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Edingburgh Educational Institute',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'El Dorado Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'El Dorado Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Elizabeth\'s College Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Emmanuel Polytechnic, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Excel Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Excelsior Private School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Exel Edu Center, Chaguanas',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Exel Edu Center, Curepe',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Fatima College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Five Rivers Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Fyzabad Anglican Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Fyzabad Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Gasparillo Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Goodwood High',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Guaico Government Secondary School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Guayaguayare High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Harmon School of S.D.A, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Hillview College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 8,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Holy Cross College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Holy Faith Convent, Couva',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Holy Faith Convent, Penal',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Holy Name Convent, Point Fortin',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Holy Name Convent, Port of Spain',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Iere High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 8,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'International School of POS',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Johnsons Finishing School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'JOSHUA CHRISTIAN SCHOOL',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'La Romain High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Lakshmi Girls\' Hindu School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Light & Life Pentecostal High, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 6,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Malabar Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Malick Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Manzanilla High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Maple Leaf International School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Marabella Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Marabella Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mason Hall High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Matelot Community School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mathura High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mayaro Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Miracle Ministries High School, Couva',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 6,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Modern Business College, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Moruga Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Morvant/Laventille Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mt. Hope Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mucurapo Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Mucurapo Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Naparima Boys\' College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 8,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Naparima Girls\' High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 8,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'NATIONAL ACADEMY OF BUSINESS ARTS & COMPUTING',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'North Eastern College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'North Gate College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'O.W.T.U. Butler Rienzi Labour College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Open Bible High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Palo Seco Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Parvatie Girls\' Hindu College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Penal Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Pentecostal Institute of Learning',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Phoenix Academy',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Pleasantville Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Point Fortin Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Point Fortin Senior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Polytechnic Sixth Form',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Presentation College, Chaguanas',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Presentation College, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Preysal High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Princes Town Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Princes Town Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Providence Girls\' Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Qualitative Arima',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Queen\'s Royal College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Rafeek Memorial T.M.L School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Rio Claro College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Rio Claro High',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Roxborough Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Russel Latapy Secondary School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'San Fernando East Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'San Fernando Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'San Fernando Secondary Comprehnsive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'San Juan Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'San Juan Gov\'t Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Sangre Grande Busines College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Sangre Grande Educational Institute Limited',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Sangre Grande Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Saraswatie Girls Hindu College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Scarborough Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Shiva Boys\' Hindu College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Signal Hill Secondary Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Siparia Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Siparia Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'South East Port-of-Spain',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Southern Academy of S.D.A',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Southern Community College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Speyside High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St Bede\'s Vocational',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'ST KEVIN\'S COLLEGE',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'ST. ANDREW\'S HIGH SCHOOL',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Andrews Academy, Chaguanas',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Andrews College, Sangre Grande',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Anthony\'s College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Augustine Community College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Augustine Girls\' High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 8,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Augustine Senior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Benedict\'s College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Charles High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'ST. DOMINIC SAVIO COLLEGE',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Dominics Convent',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Francois Girls\' College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. George\'s College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. James Gov\'t Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Joseph College, St Joseph',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Joseph Convent, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Joseph Convent, St Joseph',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Joseph Convent, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Joseph\'s Convent, Port of Spain',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Martin\'s De Porres Girls High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Mary\'s College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 9,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'St. Stephen\'s College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Ste. Madeleine Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Success/Laventille Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'SWAHA Educational Institute',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Swaha Hindu College, Sangre Grande',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Tabaquite Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Tableland High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'THE PROFESSIONAL INSTITUTE OF MARKETING AND BUSINESS STUDIES',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),

            ],
            [
                'name'=> 'THE WEST INDIES SCHOOL OF THEOLOGY',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Toco Composite',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Tranquillity Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'TRINIDAD & TOBAGO SERVICE EDU FACILITY',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Trinity College East',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Trinity College, Maraval',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 2,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Tunapuna Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'U.W.I. Sixth Form, San Fernando',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'U.W.I. Sixth Form, St Augustine',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'U.W.I. Sixth Form, Tobago',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 7,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Union Claxton Bay Senior Comprehensive',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 8,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Upper Level Educational Institute',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Valencia High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 2,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Vessigny Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 6,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Vishnu Boys Hindu College',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 5,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Waterloo High School',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 1,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'West End Academy',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 9,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Williamsville Junior Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 4,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Woodbrook Government Secondary',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 4,
                'school_district_id'=> 3,
                'description' => '',
                'created_at' =>  now(),
            ],
            [
                'name'=> 'Zenith Educational Institute',
                'slug' => null,
                'school_level_id' => 2,
                'school_type_id'=> 7,
                'school_district_id'=> 5,
                'description' => '',
                'created_at' =>  now(),
            ]
        ];
        School::insert($secondarySchools);
    }
}
