<?php
namespace Database\Seeders\service_data\serviceperson_job\establishment;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CareerPathEstablishmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::transaction(function () {
            DB::table('career_path_establishment')->insert([
                // 1. Infantry Rifleman
                ['career_path_id' => 1, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 1, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 2. Support Weapons Gunner
                ['career_path_id' => 2, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 2, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 3. Physical Training Instructo
                ['career_path_id' => 3, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 3, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 4. Military Training Instructo
                ['career_path_id' => 4, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 4, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 5. Operations Op
                ['career_path_id' => 5, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 5, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 6. All Source Intelligenc
                ['career_path_id' => 6, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 6, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 7. Counter-Intelligenc
                ['career_path_id' => 7, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 7, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 8. Special Jungle Operation
                ['career_path_id' => 8, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 8, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 9. Special Urban Operation
                ['career_path_id' => 9, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 9, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 10. Special Clandestine Operations
                ['career_path_id' => 10, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 10, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 11. Special Operations Training
                ['career_path_id' => 11, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 11, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 12. Special Sniper Support
                ['career_path_id' => 12, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 12, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 13. Military Police
                ['career_path_id' => 13, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 13, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 14. CID Special Agents
                ['career_path_id' => 14, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 14, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 15. Intern and Reset
                ['career_path_id' => 15, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 15, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 16. Dog Handlers	K-9 Handler
                ['career_path_id' => 16, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 16, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 17. Investigations
                ['career_path_id' => 17, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 17, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 18. Administrative Services	Admin Staff
                ['career_path_id' => 18, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 18, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 19. Human Resources / Organisation Development
                ['career_path_id' => 19, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 19, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 20. Signals and Telecommunications\
                ['career_path_id' => 20, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 20, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 21. Information and Knowledge Management
                ['career_path_id' => 21, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 21, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 22. Medical
                ['career_path_id' => 22, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 22, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 23. Social Services
                ['career_path_id' => 23, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 23, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 24. Regimental Band
                ['career_path_id' => 24, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 24, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 25. Corps of Drums
                ['career_path_id' => 25, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 26. Steal Orchestra
                ['career_path_id' => 26, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 26, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 27. Supply and Financial Management
                ['career_path_id' => 27, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 27, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 28. Warehousing and Storage
                ['career_path_id' => 28, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 28, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 29. Material and Clothing Services
                ['career_path_id' => 29, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 29, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 30. Dispatch Riders
                ['career_path_id' => 30, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 30, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 31. Drivers
                ['career_path_id' => 31, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 31, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 32. Chefs
                ['career_path_id' => 32, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 32, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 33. Stewards
                ['career_path_id' => 33, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 33, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 34. Carpenters
                ['career_path_id' => 34, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 34, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 35. Masons
                ['career_path_id' => 25, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 25, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 36. Plumbers
                ['career_path_id' => 36, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 36, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 37. Welders
                ['career_path_id' => 37, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 37, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 38. Operators/Drivers
                ['career_path_id' => 38, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 38, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 39. Combat Engineers
                ['career_path_id' => 39, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 39, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 40. Mechanics
                ['career_path_id' => 40, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 40, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 41. Surveyors
                ['career_path_id' => 41, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 41, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 42. Draughtsmen
                ['career_path_id' => 42, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 42, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 43. Health, Safety, Security and the Environment
                ['career_path_id' => 43, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 43, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 44. Electricians
                ['career_path_id' => 44, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 44, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 45. Auto Electricians
                ['career_path_id' => 45, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 45, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 46. Air Condition/Refrigeration Technicians
                ['career_path_id' => 46, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 46, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 47. Machinists
                ['career_path_id' => 47, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 47, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 48. Auto Body Technicians
                ['career_path_id' => 48, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 48, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()],
                // 49. Battery and Tyre Technicians
                ['career_path_id' => 49, 'rank_id'   => 2, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 3, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 4, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 5, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 6, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 7, 'establishment' => 0, 'created_at' => now()],
                ['career_path_id' => 49, 'rank_id'   => 8, 'establishment' => 0, 'created_at' => now()]
            ]);
        });
    }
}
